plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/karencastillo/Documents/Documents - Karen's MacBook Pro/BYU/Electives/professional project/portfolio"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]